#!/usr/bin/fish
cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -march=sandybridge -static" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -g" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-15 $argv
#cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -static" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -g" -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_CXX_COMPILER=/usr/lib/ccache/bin/g++ $argv
#cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -static" $argv

