#!/usr/bin/fish

# Ubuntu, clang16, dynamic:
cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -march=sandybridge -static" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -g" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-16 $argv

# Alpine, musl, gcc11, static:
#cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -march=sandybridge -static" -DCMAKE_CXX_COMPILER=/usr/lib/ccache/bin/g++ $argv

# Alpine, musl perf, clang16, static:
#cmake .. -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG -g -march=sandybridge" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -g" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_CXX_COMPILER=/usr/lib/ccache/bin/clang++-16 $argv

